### ISSUE TITLE
Number/dash suffixes in comments are stripped

### ISSUE THREAD

**Issue by JLtimeless** [coder-mike/sublime-center-comment#3]
### Description

If a comment ends in a suffix containing only spaces, dashes, or numbers, that suffix is stripped.
### Examples

`//- JSmith 2015-05-27`
expands to
`//---------------------------------- JSmith -----------------------------------`

`//* Ticket TSTPRJ-123`
expands to
`//******************************* Ticket TSTPRJ *******************************`
### Environment

```
Sublime Text 3 Build 3083
Windows 8.1 64bit
```

**Comment by coder-mike** [comment]
Hi JLtimeless,

Thanks for taking the time to raise this issue. I think I've resolved the problem now. Let me know if you have any more problems with it.

**Comment by JLtimeless** [comment]
Hey Mike, just updated and issue appears to be resolved...thanks!
